export const fontsToLoad = {
  'Pretendard-Medium': require('../../assets/fonts/Pretendard-Medium.ttf'),
  'Pretendard-Regular': require('../../assets/fonts/Pretendard-Regular.ttf'),
  'Pretendard-SemiBold': require('../../assets/fonts/Pretendard-SemiBold.ttf'),
  'Pretendard-Bold': require('../../assets/fonts/Pretendard-Bold.ttf'),
  'NanumPenScript-Regular': require('../../assets/fonts/NanumPenScript-Regular.ttf'),
  'RobotoMono-Regular': require('../../assets/fonts/RobotoMono-Regular.ttf'),
  'RobotoMono-Medium': require('../../assets/fonts/RobotoMono-Medium.ttf'),
  'RobotoMono-SemiBold': require('../../assets/fonts/RobotoMono-SemiBold.ttf'),
  'RobotoMono-Bold': require('../../assets/fonts/RobotoMono-Bold.ttf'),
  'Esamanru-Light': require('../../assets/fonts/Esamanru-Light.otf'),
  'Esamanru-Medium': require('../../assets/fonts/Esamanru-Medium.otf'),
  'Esamanru-Bold': require('../../assets/fonts/Esamanru-Bold.otf'),
  'LeeSeoyun-Regular': require('../../assets/fonts/LeeSeoyun-Regular.ttf'),
  'Inter-Regular': require('@tamagui/font-inter/otf/Inter-Regular.otf'),
  'Inter-Medium': require('@tamagui/font-inter/otf/Inter-Medium.otf'),
  'Inter-Bold': require('@tamagui/font-inter/otf/Inter-Bold.otf'),
  'Inter-SemiBold': require('@tamagui/font-inter/otf/Inter-SemiBold.otf'),
}
